version: '3'

services:
  erm_database:
    image: postgres:14
    hostname: erm_database
    container_name: erm_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: erm
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

  erm_backend:
    image: golang:1.17
    hostname: erm_backend
    container_name: erm_backend
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build -o app ./cmd/api/' -command='./app'
    volumes:
      - ./webroot/erm_backend:/usr/local/go/src/app:rw
    ports:
      - "9000:9000"
    depends_on:
      - erm_database

  erm_frontend:
    image: node:16
    hostname: erm_frontend
    container_name: erm_frontend
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm install
        npm start
    volumes:
      - ./webroot/erm_frontend:/usr/src/app:rw
    ports:
      - "3000:3000"
