const FlashActionTypes = {
    ADD_SUCCESS_MESSAGE: 'ADD_SUCCESS_MESSAGE',
    ADD_WARNING_MESSAGE: 'ADD_WARNING_MESSAGE',
    ADD_ERROR_MESSAGE: 'ADD_ERROR_MESSAGE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',
};

export default FlashActionTypes;